services:
  - type: web
    name: flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: MALLOC_TRIM_THRESHOLD_
        value: "65536"
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 0.5
